#invocation_name: ready media # if commented, invocation name is read from intents.json
substitute_domain: mylocaldevice.minidlna
root_xml_url: http://192.168.0.2:8200/rootDesc.xml
similarity_threshold: 0.8
port: 443 # amazon wants the endpoint to be accessible via port 443, change this only if you have a good reason, for example when using a web proxy
ssl_private_key: private-key.pem
ssl_certificate: certificate.pem
log_level: 10 # logging.DEBUG=10