#invocation_name: ready media # if commented, invocation name is read from intents.json
endpoint_domain: your_endpoint_domain.com
#bind_ip_address: "::" # use quotation for ipv6
bind_ip_address: 0.0.0.0 
root_xml_url: http://127.0.0.1:8200/rootDesc.xml
similarity_threshold: 0.8
port: 443 # amazon wants the endpoint to be accessible via port 443, change this only if you have a good reason, for example when using a web proxy
ssl_private_key: private-key.pem
ssl_certificate: certificate.pem
log_level: 10 # logging.DEBUG=10
skill_id: <your_skill_id> # find your skill id in the alexa development console